const UNITS = {
    Metric: 'M',
    Fahrenheit: 'I',
    Scientific: 'S',
}

const LANG = {
    "English": 'en',
    "Spanish": 'es',
    "Arabic": 'ar',
    "Azerbaijani": 'az',
    "Belarusian": 'be',
    "Bulgarian": 'bg',
    "Bosnian": 'bs',
    "Catalan": 'ca',
    "Czech": 'cz',
    "Danish": 'da',
    "German": 'de',
    "Finnish": 'fi',
    "French": 'fr',
    "Greek": 'el',
    "Spanish": 'es',
    "Estonian": 'et',
    "Japanese": 'ja',
    "Croation": 'hr',
    "Hungarian": 'hu',
    "Indonesian": 'id',
    "Italian": 'it',
    "Icelandic": 'is',
    "Hebrew": 'iw',
    "Cornish": 'kw',
    "Lithuanian": 'lt',
    "Norwegian Bokmål": 'nb',
    "Dutch": 'nl',
    "Polish": 'pl',
    "Portuguese": 'pt',
    "Romanian": 'ro',
    "Russian": 'ru',
    "Slovak": 'sk',
    "Slovenian": 'sl',
    "Serbian": 'sr',
    "Swedish": 'sv',
    "Turkish": 'tr',
    "Ukrainian": 'uk',
    "Chinese (Simplified)": 'zh',
    "Chinese (Traditional)": 'zh-tw',
}

module.exports = {
    LANG,
    UNITS,
}